Update run time dep to package.yml
getsolus/packages pull request #1148
Opened 2023-12-29 22:31 UTC by clivej

Adding python-packaging as a run time dep for the Tor Browser installer

**Summary**

Installer currently does nothing on a fresh Solus install.  On investigation the system is missing python-packaging throwing the following error in terminal:

  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/launcher.py", line 40, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

**Test Plan**

Installed python-packaging and the installer completes

**Checklist**

- Installer now completes and starts TOR browser as designed

2023-12-29 22:32 UTC, ReillyBrogan requested changes
You need to bump the release number, build it, and then commit the updated pspec file as well.

2023-12-29 22:38 UTC, clivej commented
Not sure how to do that using this new work flow.  Currently don't have a build environment set-up as having issues connecting it to GitHub for some reason, hence trying to do it from website GUI!

2023-12-30 15:29 UTC, malfisya commented
@clivej This will help https://help.getsol.us/docs/packaging/

2024-01-01 16:06 UTC, clivej commented
> @clivej This will help https://help.getsol.us/docs/packaging/

I have tried that, having problems connecting to GitHub.  Might be my 2FA / yubikey setup, not sure.

2024-02-16 16:44 UTC, Staudey commented
This was superseded by getsolus/packages/pull/1545 and can be closed now. Thank you for the heads-up about the missing rundep, @clivej!

2024-02-16 16:44 UTC, closed without merging