Keysmith - initial inclusion
getsolus/packages pull request #1226
Opened 2024-01-08 11:46 UTC by Justinzobel

**Summary**

Initial inclusion

**Test Plan**

Copied my TOTP keys from another device and tested, all OK

**Checklist**

- [x] Package was built and tested against unstable

2024-01-08 15:56 UTC, ReillyBrogan requested changes
I also see that the plasma-wallpapers commit is still in the "not in main" part of this branch (see the "Commits" tab on the PR). Given that plasma-wallpapers has already been merged into main I think this likely just needs a rebase. Try the following and see if it fixes it:
```
git fetch origin
git rebase origin/main
git push --force
```

2024-01-08 15:56 UTC, ReillyBrogan commented on packages/k/keysmith/package.yml
> +    - pkgconfig(Qt5Core)
Capitalized pkgconfig deps are ordered above lowercase ones, so the three `Qt5*` deps should be above the `libsodium` one.

2024-01-08 15:56 UTC, ReillyBrogan commented on packages/k/keysmith/package.yml
> +    - kdbusaddons-devel
These three need to be in alphabetical order.

2024-01-08 17:25 UTC, ReillyBrogan commented
I assume that the reason the plasma-wallpapers commit is included in this branch is because you created your branch from the plasma-wallpapers one. May I introduce you to the following command:
```
git switch -c new-branch-name origin/main
```
Which will create a new branch named `new-branch-name` and then switch to it. `origin/main` is the starting point for the new branch instead of the current HEAD. Bonus points if you run `git fetch origin` first so that the branch is fully up-to-date with Github.

2024-01-10 01:39 UTC, Justinzobel commented
Fixed in the other PR.

2024-01-10 01:39 UTC, closed without merging