Update snapd to 2.61.1
getsolus/packages pull request #1483
Opened 2024-02-01 14:18 UTC by zyga

**Summary**

Update snapd to 2.61.1

**Test Plan**

I've tested this on a virtual machine running unstable.
I've installed and played with the snaps "ohmygiraffe" and "okular".

**Checklist**

- [x] Package was built and tested against unstable

2024-02-01 14:19 UTC, zyga commented on packages/s/snapd/pspec_x86_64.xml
> -            <Name>Joey Riches</Name>
I don't know if this is customary. Please clarify if this should be in the PR.

2024-02-01 16:45 UTC, davidjharder requested changes
Excellent first PR. A few small things:

- We want one commit per package on a PR: commit "snapd: sort builddeps properly" should be squashed so that there is only "snapd: Update to 2.61.1" on this PR
- Please copy the changelog you included in the first commit message, and paste it under "summary" in the PR description

2024-02-01 21:11 UTC, zyga commented
@davidjharder done, thank you for the clear instructions!

2024-02-03 03:47 UTC, davidjharder approved these changes
Looks good, thanks

2024-02-03 03:47 UTC, merged