Update libicu to 74.2 & rebuilds
getsolus/packages pull request #1564
Opened 2024-02-07 13:41 UTC by joebonrichie

**Summary**

libicu 74 & rebuilds

**Test Plan**

Install, no borky.

**Checklist**

- [x] Package was built and tested against unstable

2024-02-07 13:46 UTC, joebonrichie commented
will reenable libicu support in libxml2 after landing this

2024-02-07 15:45 UTC, EbonJaeger requested changes
One package has a double-bump. Looks good, aside from 29 of the pspec files not having the packager information set. Not sure what we want to do about that.

2024-02-07 15:45 UTC, EbonJaeger commented on packages/py/pyicu/package.yml
> +release    : 30
Release double-bumped

2024-02-07 17:48 UTC, ReillyBrogan commented
I'll fix-up the pspecs for this.

2024-02-08 04:10 UTC, ReillyBrogan approved these changes

2024-02-08 04:10 UTC, merged