kio-admin: Initial commit at 1.0.0
getsolus/packages pull request #1740
Opened 2024-02-26 10:51 UTC by Justinzobel

**Summary**

Adds kio-admin, fixes #483

**Test Plan**

Used kio-admin to create a folder in a root-only-writable area of the disk.

**Checklist**

- [x] Package was built and tested against unstable

2024-02-26 17:45 UTC, sheepman4267 commented
It looks to me like there are quite a few newer tags here: https://invent.kde.org/system/kio-admin/-/tags

I realize the old version was linked in the issue, but should we be using a newer one now?

2024-02-26 22:50 UTC, Justinzobel commented
Ah, I didn't realise it was moved into gear. I checked for new versions in the index of where the tarball was but didn't see any. I'll update.

2024-02-27 17:48 UTC, davidjharder requested changes
See builddep order warning

2024-02-27 21:54 UTC, davidjharder approved these changes

2024-02-27 21:55 UTC, merged