hunspell-el: include homepage
getsolus/packages pull request #1918
Opened 2024-03-17 15:31 UTC by androidnisse

**Summary**
- Inclusion of "homepage" to package.yml
- Part of https://github.com/getsolus/packages/issues/411

**Test plan**
- Checked that homepage was added correctly

**Check list**
- [X] Package was built and tested against unstable

2024-03-20 20:33 UTC, algent-al requested changes

2024-03-20 20:33 UTC, algent-al commented on packages/h/hunspell-el/package.yml
> +version    : 0.9.0
No need for extra `.0`.  Corrected should be `version    : '0.9'`

2024-03-24 14:37 UTC, androidnisse commented
@algent-al should be fixed now.

2024-03-24 20:49 UTC, algent-al approved these changes
LGTM, thanks!

2024-03-24 20:50 UTC, algent-al approved these changes
LGTM, thanks!

2024-03-25 17:59 UTC, androidnisse commented
@algent-al could this be merged now?

2024-03-25 21:16 UTC, merged