keepassxc: update to 2.7.7
getsolus/packages pull request #1924
Opened 2024-03-18 19:52 UTC by TraceyC77

**Summary**

Update keepassxc, add monitoring.yml

**Changelog**

Changes

    Support USB Hotplug for Hardware Key interface
    Support 1PUX and Bitwarden import
    Browser: Add support for PassKeys [#8825, #9987, #10318]
    Build System: Move to vcpkg manifest mode

Fixes

    Fix multiple TOTP issues
    Fix focus loss on save when the editor is not visible anymore
    Fix visual when removing entry from history
    Fix first entry is not selected when a search is performed
    Prevent scrollbars on entry drag/drop
    Prevent duplicate characters in "Also choose from" field of password generator
    Security: Prevent byte-by-byte and attachment inference side channel attacks
    Browser: Fix raising Update Entry messagebox
    Browser: Fix bugs when returning credentials
    Browser: Fix crash on database open from browser
    Browser: Fix support for referenced URL fields
    MacOS: Fix crash when changing highlight/accent color
    MacOS: Fix TouchID appearance depending on lid open/closed
    Windows: Fix terminating KeePassXC processes with MSI installer
    FdoSecrets: Fix database merge crash when enabled

Full changelog available [here](https://github.com/keepassxreboot/keepassxc/releases)

**Test Plan**

Ran keepassxc, unlocked database. Verified browser extension could connect.

**Checklist**

- [x] Package was built and tested against unstable

2024-03-19 00:34 UTC, HarveyDevel requested changes

2024-03-19 00:34 UTC, HarveyDevel commented on packages/k/keepassxc/monitoring.yml
Empty file?

2024-03-25 00:45 UTC, TraceyC77 commented on packages/k/keepassxc/monitoring.yml
Wups. Fixed.

2024-03-25 00:52 UTC, HarveyDevel approved these changes
LGTM, thanks.

2024-03-25 00:52 UTC, merged