pyenchant: update to 3.2.2
getsolus/packages pull request #2034
Opened 2024-03-30 08:02 UTC by androidnisse

**Summary**
- Release notes can be found [here](https://pyenchant.github.io/pyenchant/changelog.html).

**Test plan**
- Installed and loaded rednotebook that is dependant on this and checked spell checking.

**Check list**
- [X] Package was built and tested against unstable.

2024-03-30 20:35 UTC, algent-al requested changes

2024-03-30 20:35 UTC, algent-al commented on packages/py/pyenchant/package.yml
> +    - https://files.pythonhosted.org/packages/b1/a3/86763b6350727ca81c8fcc5bb5bccee416e902e0085dc7a902c81233717e/pyenchant-3.2.2.tar.gz : 1cf830c6614362a78aab78d50eaf7c6c93831369c52e1bb64ffae1df0341e
Please use this source instead: https://files.pythonhosted.org/packages/source/p/pyenchant/pyenchant-3.2.2.tar.gz

2024-03-31 06:32 UTC, androidnisse commented
@algent-al fixed source.

2024-03-31 20:23 UTC, algent-al approved these changes
LGTM, thanks!

2024-03-31 20:23 UTC, merged