util-macros: include homepage
getsolus/packages pull request #2046
Opened 2024-03-31 07:46 UTC by androidnisse

**Summary**
- Inclusion of "homepage" to package.yml
- Part of https://github.com/getsolus/packages/issues/411

**Test plan**
- Checked that homepage was added correctly

**Check list**
- [X] Package was built and tested against unstable

2024-03-31 20:29 UTC, algent-al requested changes

2024-03-31 20:29 UTC, algent-al commented on packages/u/util-macros/package.yml
>  license    : GPL-3.0
Let's fix the license too. `GPL-3.0-or-later`

2024-04-01 08:13 UTC, androidnisse commented
@algent-al License fixed.

2024-04-01 19:59 UTC, algent-al approved these changes
LGTM, thanks!

2024-04-01 19:59 UTC, merged