sof-firmware: update to 2.9
getsolus/packages pull request #2110
Opened 2024-04-04 01:47 UTC by TraceyC77

**Summary**

For v2.9 series, the following new topology files have been added since v2.8:

v2.9.x/sof-ipc4-tplg-v2.9
├── sof-hda-generic-ace1-2ch.tplg
├── sof-hda-generic-ace1-4ch.tplg
├── sof-hda-generic-cavs25-2ch.tplg
├── sof-hda-generic-cavs25-4ch.tplg
├── sof-mtl-es83x6-ssp1-hdmi-ssp02.tplg
├── sof-mtl-hdmi-ssp02.tplg

Full release notes [here](https://github.com/thesofproject/sof-bin/releases)

Solus: Add monitoring.yml

**Test Plan**

Verified firmware files were installed to correct paths. Restarted pipewire.
    systemctl --user restart pipewire.service
Listened to music and triggered system sounds to verify that sound still works.

**Checklist**

- [x] Package was built and tested against unstable

2024-04-04 14:38 UTC, EbonJaeger requested changes

2024-04-04 14:38 UTC, EbonJaeger commented on packages/s/sof-firmware/monitoring.yml
> +  cpe: ~
Could you add a newline here, please? Thanks!

2024-04-04 14:38 UTC, EbonJaeger commented on packages/s/sof-firmware/pspec_x86_64.xml
> +            <Path fileType="data">/lib/firmware/intel/sof-ace-tplg</Path>
Were these moved or removed upstream? Looks like we're just installing an empty directory now.

2024-05-16 22:16 UTC, ReillyBrogan approved these changes

2024-05-16 22:16 UTC, merged