Update gpsbabel
getsolus/packages pull request #2448
Opened 2024-05-02 06:52 UTC by malfisya

**Summary**

- shapelib: Add at 1.6.0
- gpsbabel: Update to 1.9.0

2024-05-02 11:11 UTC, androidnisse commented
Resolves https://github.com/getsolus/packages/issues/2284

2024-05-06 23:12 UTC, davidjharder requested changes
Some small things. Great work on this.

2024-05-06 23:12 UTC, davidjharder commented on packages/s/shapelib/pspec_x86_64.xml
> +            <Path fileType="library">/usr/lib64/libshp.a</Path>
Don't need the static libs

I would say we can ditch the `-devel` package and just pattern everything into `shapelib`

2024-05-06 23:12 UTC, davidjharder commented on packages/s/shapelib/monitoring.yml
> +  rss: ~
Small nit: There is a github repo we can use: https://github.com/OSGeo/shapelib for a feed

2024-05-07 13:33 UTC, davidjharder approved these changes
LGTM, thanks!

2024-05-07 13:33 UTC, merged