[RFC] vala-panel-appmenu: Update to 24.02
getsolus/packages pull request #2609
Opened 2024-05-17 23:22 UTC by malfisya

**Summary**

- Switch to new version scheme
- BAMF now removed. Importer now a standalone library.

**Test Plan**

Install on Budgie, XFCE, and MATE

**Checklist**

- [x] Package was built and tested against unstable

2024-05-17 23:23 UTC, malfisya commented on packages/v/vala-panel-appmenu/pspec_x86_64.xml
> +            <Path fileType="data">/usr/share/licenses/appmenu-gtk-module/LICENSE</Path>
Should I remove these?

2024-05-17 23:24 UTC, malfisya commented on packages/v/vala-panel-appmenu/pspec_x86_64.xml
> +            <Path fileType="doc">/usr/share/doc/vala-panel-appmenu/README.md</Path>
Remove this ?

2024-05-17 23:25 UTC, malfisya commented
Also now we have XFCE edition, should we build the XFCE Panel too ?

2024-05-18 00:06 UTC, EbonJaeger commented
XFCE panel support would be nice, for anyone who may want it.

2024-05-18 02:52 UTC, malfisya commented on packages/v/vala-panel-appmenu/pspec_x86_64.xml
> +            <Path fileType="data">/usr/share/licenses/appmenu-gtk-module/LICENSE</Path>
Remove this too ?

2024-05-18 02:53 UTC, malfisya commented on packages/v/vala-panel-appmenu/pspec_x86_64.xml
> +            <Path fileType="data">/usr/share/licenses/vala-panel-appmenu/LICENSE</Path>
Remove this too ?

2024-05-18 03:45 UTC, malfisya commented
I did test this, but need someone that actually use it to see if there is behaiour changes.

2024-05-21 16:51 UTC, EbonJaeger approved these changes
LGTM, thanks!

2024-05-21 16:52 UTC, EbonJaeger requested changes
Actually, could I ask you to add a `monitoring.yml` file?

2024-05-22 13:46 UTC, EbonJaeger approved these changes
LGTM, thanks!

2024-05-22 13:46 UTC, merged