msbuild: build fix & update to 16.9
getsolus/packages pull request #2714
Opened 2024-05-26 00:44 UTC by nelsontkq

**Summary**

Many internal changes between 16.8->16.9. Main reason for update is that it's the one mono 16.12.0.* expects.

Full list of changes [available here](https://github.com/dotnet/msbuild/blob/main/documentation/Changelog.md)

solves #2622 

**Test Plan**

 - build a few projects
 - build godot and confirm working

**Checklist**

- [x] Package was built and tested against unstable

2024-05-26 01:01 UTC, davidjharder requested changes
Thanks for fixing this. One small issue

2024-05-26 01:01 UTC, davidjharder commented on packages/m/mono-msbuild/package.yml
>  builddeps  :
These should be re-ordered, see Actions warning

2024-05-26 21:43 UTC, nelsontkq commented
@davidjharder fixed!

2024-05-27 16:27 UTC, davidjharder approved these changes
Thanks!

2024-05-27 16:27 UTC, merged