libffi: Update to 3.4.6
getsolus/packages pull request #2785
Opened 2024-05-29 13:49 UTC by malfisya

**Summary**

- Release notes - [3.4.6](https://github.com/libffi/libffi/releases/tag/v3.4.6) - [3.4.5](https://github.com/libffi/libffi/releases/tag/v3.4.5) - [3.4.4](https://github.com/libffi/libffi/releases/tag/v3.4.4) - [3.4.3](https://github.com/libffi/libffi/releases/tag/v3.4.3) - [3.4.2](https://github.com/libffi/libffi/releases/tag/v3.4.2)
- Add `homepage` key to `package.yml` (Part of getsolus/packages#411)
- Add monitoring.yml

**Test Plan**

Rebuild all revdeps

**Checklist**

- [x] Package was built and tested against unstable

2024-05-29 14:13 UTC, malfisya commented
It needs a rebuild of several chonky packages that I am not sure my PC can handle:
- [ ] ruby
- [ ] ruby-ffi
- [ ] libffi-devel
- [ ] haskell-cabal-install
- [ ] python2-gobject
- [ ] ghc
- [ ] python-gobject2
- [ ] libp11-kit
- [ ] thunderbird
- [ ] glib2
- [ ] yosys-devel
- [ ] libffi-dbginfo
- [ ] python-gobject
- [ ] llvm-15-devel
- [ ] crystal
- [ ] python2-cffi
- [ ] pandoc
- [ ] yosys
- [ ] shellcheck
- [ ] gjs
- [ ] guile
- [ ] python-cffi
- [ ] python3
- [ ] firefox
- [ ] xmonad
- [ ] wayland
- [ ] pandoc-crossref
- [ ] libffi-32bit
- [ ] llvm
- [ ] gobject-introspection
- [ ] perl-glib-object-introspection
- [ ] rocm-llvm
- [ ] llvm-15

2024-05-29 19:56 UTC, davidjharder commented
I removed the "Help Wanted" tag because this stack will probably have to wait until after 4.6, given size and complexity

2024-12-18 00:12 UTC, ReillyBrogan requested changes

2024-12-18 00:13 UTC, ReillyBrogan commented
Sorry, apparently I forgot to actually submit the review. At least libffi is a fast build.

2024-12-18 00:38 UTC, ReillyBrogan approved these changes

2024-12-18 00:53 UTC, merged