nsxiv: initial inclusion at version 32
getsolus/packages pull request #3022
Opened 2024-06-16 18:59 UTC by androidnisse

**Summary**
- Initial inclusion
- Replaces sxiv

**Test Plan**
- Installed, opened an image, read the man pages.

**Checklist**

- [X] Package was built and tested against unstable

**Packaging notes**
- Resolves https://github.com/getsolus/packages/issues/3007

2024-06-25 01:18 UTC, malfisya requested changes
A few changes:
- Let's use a better comit message:
```
package: Add at v1.0
```
- This package include a desktop file but doesn't ship an appstream metainfo file. Can you add that? There is an example in this [issue](https://github.com/getsolus/packages/issues/1389). I usually use this [tool](https://www.freedesktop.org/software/appstream/metainfocreator/#/guiapp) to create appstream metainfo.

2024-06-25 15:08 UTC, androidnisse commented
> A few changes:
> 
>     * Let's use a better comit message:
> 
> 
> ```
> package: Add at v1.0
> ```
> 
>     * This package include a desktop file but doesn't ship an appstream metainfo file. Can you add that? There is an example in this [issue](https://github.com/getsolus/packages/issues/1389). I usually use this [tool](https://www.freedesktop.org/software/appstream/metainfocreator/#/guiapp) to create appstream metainfo.

Does it work like I did now?

2024-06-25 23:09 UTC, malfisya requested changes
Yes, the appstream metainfo is valid. I just noticed this one small thing, other than that it looks good. Cheers!

2024-06-25 23:09 UTC, malfisya commented on packages/n/nsxiv/package.yml
> +    - sxiv
Lets put this at the bottom

2024-06-26 06:27 UTC, malfisya approved these changes
Looks good. Thanks!

2024-06-26 06:28 UTC, malfisya commented
Oh, do you want to include `sxiv` deprecation here or file seperate PR? We might as well do it soon.

2024-06-26 06:34 UTC, androidnisse commented
> Oh, do you want to include `sxiv` deprecation here or file seperate PR? We might as well do it soon.

I can file another soon for deprecation.

2024-06-26 09:04 UTC, merged