font-inter-ttf: Initial inclusion at 4.0
getsolus/packages pull request #3033
Opened 2024-06-17 18:26 UTC by garaevdi

**Summary**

- Add `font-inter-ttf` at 4.0
- Resolves getsolus/packages#2980

**Test plan**

- Change GNOME's interface font via GNOME Tweaks
- Change Budgie's interface font via Budgie desktop settings

**Checklist**

- [x] Package was built and tested against unstable

2024-06-19 18:20 UTC, EbonJaeger reviewed
There are a bunch of other font files in `extras/ttf` of the download. Do we want any of those?

2024-06-19 23:58 UTC, EbonJaeger requested changes

2024-06-19 23:58 UTC, EbonJaeger commented on packages/f/font-inter-ttf/pspec_x86_64.xml
> +            <Email>no.email.set.in.config</Email>
It looks like you don't have an email set in the [packager file](https://help.getsol.us/docs/packaging/prepare-for-packaging#setting-up-the-packager-file). Could you set one, please? Thanks!

2024-06-21 14:42 UTC, garaevdi commented
> There are a bunch of other font files in `extras/ttf` of the download. Do we want any of those?

I checked [GNOME's mr](https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/merge_requests/85/diffs) one more time, and I think that actually they want to use static version.

2024-06-21 23:34 UTC, EbonJaeger requested changes
Just noticed one small nit. Other than that, it looks good!

2024-06-21 23:34 UTC, EbonJaeger commented on packages/f/font-inter-ttf/package.yml
> +        install -Dm00644 $pkgfiles/inter.metainfo.xml $installdir/usr/share/metainfo/inter.metainfo.xml
The indentation should be 4 spaces.

2024-06-23 13:30 UTC, EbonJaeger approved these changes
LGTM, thanks!

2024-06-23 13:31 UTC, merged