nvidia-470-glx-driver: Enable per-kernel initrd, add usr-merge changes
getsolus/packages pull request #3117
Opened 2024-06-28 21:00 UTC by Staudey

**Summary**

This adds the same changes already applied to the glx and beta driver. Minus things like GSP firmware, which is not useful on this old driver branch.

**Test Plan**
- Rebooted
- Launched Steam
- Played the games "Balatro" (Proton) and "Clustertruck" (native)

**Checklist**

- [x] Package was built and tested against unstable

2024-06-28 21:04 UTC, Staudey commented
Oops, forgot one thing, sec

2024-07-01 18:51 UTC, ReillyBrogan commented on packages/n/nvidia-470-glx-driver/pspec_x86_64.xml
> +            <Path fileType="library">/usr/lib64/kernel/initrd-com.solus-project.lts.6.6.33-247.nvidia</Path>
These files need to go into their respective kernel package

2024-07-01 18:52 UTC, ReillyBrogan requested changes
See comment

2024-07-01 19:06 UTC, Staudey commented
Whoops, good catch. One sec.

2024-07-01 19:10 UTC, Staudey commented
Done!

2024-07-01 22:58 UTC, ReillyBrogan approved these changes

2024-07-01 22:58 UTC, merged