mesa-demos: Enable everything
getsolus/packages pull request #3395
Opened 2024-07-24 11:44 UTC by joebonrichie

**Summary**
- Previously we were missing critical testing demos such as `eglgears_wayland` let's just build everthing moving forward.

**Test Plan**
- Run `eglgears_wayland`

**Checklist**

- [x] Package was built and tested against unstable

2024-07-26 20:48 UTC, ReillyBrogan commented
This increases the size of the package by 5000% from ~600KB to ~31MB. Is that really worth it to avoid having to pick and choose which ones we install?

2024-08-17 19:45 UTC, TraceyC77 requested changes
This doesn't build due to a conflict with /usr/bin/line

```
❯ sudo eopkg it *.eopkg &&\
eopkg info mesa-demos |grep -A 3 Installed\ package
Updates available, checking reverse dependencies of runtime dependencies for safety.
Installation order: mesa-demos 
Installing mesa-demos, version 9.0.0, release 79
 [✓] Syncing filesystems                                                success
 [✓] Compiling and Reloading AppArmor profiles                          success
Program terminated.
File conflicts:
/usr/bin/line from util-linux package
```

2024-08-17 19:45 UTC, TraceyC77 commented on packages/m/mesa-demos/pspec_x86_64.xml
> +            <Path fileType="executable">/usr/bin/line</Path>
This conflicts with util-linux

2025-08-23 00:36 UTC, TraceyC77 commented
@joebonrichie , are you still planning on landing this or should it be closed out?

2026-06-19 14:28 UTC, closed without merging