python-absl-py: Update to 2.1.0
getsolus/packages pull request #3424
Opened 2024-07-28 15:15 UTC by dikel

**Summary**

Updates `python-absl-py` to 2.1.0 and adds homepage url

**Test Plan**

- Run [sample app](https://github.com/abseil/abseil-py/blob/main/smoke_tests/sample_app.py) from the package repo and verified it works
- Checked homepage was added

**Checklist**

- [x] Package was built and tested against unstable

2024-08-02 13:50 UTC, malfisya requested changes
Please squash your commit. Also make sure that `python-tensorboard` can be built against this version.

2024-08-04 23:51 UTC, malfisya commented
Sorry, I meant to say can `python-tensorboard` be run with this new version? Unfortunately I already have the answer as apparently I already tried to do it [before ](https://github.com/getsolus/packages/pull/2953). The answer is no. I will defer this PR to others that are more familiar with this package. Cheers!

2024-10-31 16:41 UTC, davidjharder commented
Hey @dikel have you had time to look at this?

2024-11-04 08:13 UTC, dikel commented
Hey @davidjharder, I haven't. We had a discussion in the matrix chat and IIRC we decided to leave it as draft because `python-tensorboard` was failing both with the new and the old version of `python-absl-py`. I think we should close this PR and have someone with more python experience look at it

2024-11-04 13:03 UTC, davidjharder commented
OK. Thanks for the response

2024-11-04 13:03 UTC, closed without merging