Update python-vdf and protontricks for new Steam vdf format
getsolus/packages pull request #3454
Opened 2024-08-01 20:42 UTC by Staudey

**Summary**

This updates `python-vdf` and `protontricks` so they are compatible with the new vdf format in the current Steam beta

**Test Plan**

Used `protontricks` to install components into a game's proton prefix.

**Checklist**

- [x] Package was built and tested against unstable

2024-08-17 19:59 UTC, TraceyC77 requested changes
python-vdf doesn't build

2024-08-17 19:59 UTC, TraceyC77 commented on packages/py/python-vdf/package.yml
This package fails to build on my system, looks like there's a missing dependency

```
~/YPKG/root/python-vdf/build/py3build ~/YPKG/root/python-vdf/build ~/YPKG/root/python-vdf/build/vdf-3.4
+ [[ -f setup.py ]]
+ python3 setup.py install --root=/home/build/YPKG/root/python-vdf/install
Traceback (most recent call last):
  File "/home/build/YPKG/root/python-vdf/build/py3build/setup.py", line 6, in <module>
    import vdf
ModuleNotFoundError: No module named 'vdf'
+ exit
Command '['/bin/bash', '--norc', '--noprofile', '/tmp/ypkg-installj894rq83']' returned non-zero exit status 1.
[Build] install failed for python-vdf
 ✗  Failed to build packages err="Failed to start build of package, reason: exit status 1\n"
task: Failed to run task "build": exit status 1
```

2024-08-17 20:26 UTC, Staudey commented on packages/py/python-vdf/package.yml
That is weird, it still builds perfectly fine for me. I hope this is not another of these weird _fakeroot_ issues.

2024-08-28 02:55 UTC, HarveyDevel commented on packages/py/python-vdf/package.yml
This builds fine for me too. Going to try landing it.

2024-08-28 02:56 UTC, HarveyDevel approved these changes
LGTM, thanks!

2024-08-28 02:56 UTC, merged