keyd: Add at 2.5.0
getsolus/packages pull request #3617
Opened 2024-08-18 19:24 UTC by uni-dos

**Summary**
Add keyd a key remapper for linux

**Test Plan**

- Set up a config for vim movement
- open micro and make sure capslock+vim navigation works

**Checklist**

- [x] Package was built and tested against unstable

2024-08-18 19:42 UTC, silkeh commented
Thanks for the PR. However, keep in mind that we will not take a look until the package request has been accepted or rejected (see [the note in the documentation](https://help.getsol.us/docs/packaging/creating-a-new-package/)). I have set the PR to draft to indicate this.

Additionally, this was missing a `Resolves` part in the PR description as per the [commit message format for new packages](https://help.getsol.us/docs/packaging/creating-a-new-package#commit-message-format-for-new-packages). I've edited the PR to include this.

2024-09-14 01:44 UTC, ReillyBrogan requested changes
Also needs monitoring.yml

2024-09-14 01:44 UTC, ReillyBrogan commented on packages/k/keyd/package.yml
> +    sed -e 's#@PREFIX@#/usr#' -e 's#multi-user.target#systemd-udev.service#' keyd.service.in > keyd.service
```suggestion
    sed -e "s#@PREFIX@#%PREFIX%#" -e 's#multi-user.target#systemd-udev.service#' keyd.service.in > keyd.service
```

2024-09-14 01:44 UTC, ReillyBrogan commented on packages/k/keyd/package.yml
> +    rm -r $installdir/etc/
We like to see what's happening.
```suggestion
    rm -rv $installdir/etc/
```

2024-10-21 10:11 UTC, malfisya approved these changes
LGTM. Thank you!

2024-10-21 10:14 UTC, merged