wpa_supplicant: Overhaul config
getsolus/packages pull request #369
Opened 2023-09-22 18:53 UTC by ReillyBrogan

Changes:
- Rewrite config file to be based off of the upstream defconfig. This makes merging in upstream changes easier
- Enable a large number of options aimed at increasing compatibility with as many networks as reasonably possible. Some of these were upstream defaults that were not enabled as we updated versions.
- Did four-way merge with Arch, Debian, Ubuntu, and Fedora configs to determine what was commonly enabled and modified.
- Added extra bugfix patch preventing potential reconnection after disconnecting from a network
- Changed default TLS ciphers, hopefully fixing the certificate issues once and for all
- Added eapol_test utility for debugging purposes
- Added man pages
- Removed unnecessary systemd services (only DBUS-activation is necessary on Solus)
- Remove old sleep workaround

2023-09-22 18:53 UTC, ReillyBrogan commented
Draft until after sync

2023-09-29 10:51 UTC, joebonrichie approved these changes

2023-09-29 10:53 UTC, joebonrichie commented
@EbonJaeger possibly a good idea to mention this in sync notes in case of problems or if it sorts out peeps issues with 2.10.

2023-09-29 13:46 UTC, EbonJaeger commented
Definitely. It should also be merged post-sync to get the most testing it can.

2023-09-29 15:17 UTC, GZGavinZhao reviewed
Is the `pspec_x86_64.xml` up-to-date? After I built it locally, `git diff` tells me that the file `/usr/lib/systemd/system-sleep/wpa_supplicant.sh` is removed.

2023-09-29 15:42 UTC, joebonrichie commented
> Is the `pspec_x86_64.xml` up-to-date? After I built it locally, `git diff` tells me that the file `/usr/lib/systemd/system-sleep/wpa_supplicant.sh` is removed.

Nice catch, it indeed shouldn't be there any longer.

2023-09-29 15:43 UTC, joebonrichie requested changes

2023-09-29 15:43 UTC, joebonrichie commented on packages/w/wpa_supplicant/pspec_x86_64.xml
>              <Path fileType="library">/usr/lib/systemd/system-sleep/wpa_supplicant.sh</Path>
Needs rebuilding, so this entry is removed

2023-09-29 17:41 UTC, joebonrichie approved these changes

2023-09-29 17:58 UTC, merged