pcsx2: Update to 2.0.2
getsolus/packages pull request #3855
Opened 2024-09-17 14:22 UTC by malfisya

**Summary**

- [Changes since previous version](https://github.com/PCSX2/pcsx2/compare/v1.7.5543...v2.0.2)
- [PCSX2 2.0 release blog post](https://pcsx2.net/blog/2024/pcsx2-2-release/)
- Resolves https://github.com/getsolus/packages/issues/3648

**Test Plan**

Play Crash Tag Team Racing

**Checklist**

- [x] Package was built and tested against unstable

2024-09-18 21:05 UTC, davidjharder requested changes
I see only one small thing

2024-09-18 21:05 UTC, davidjharder commented on packages/l/libbacktrace/pspec_x86_64.xml
> +            <Path fileType="library">/usr/lib64/libbacktrace.a</Path>
Let's nuke the static lib

2024-09-18 23:50 UTC, ReillyBrogan commented
Tbh since libbacktrace is inherently unstable and everything linked against it needs to be rebuilt on every update (of which they don't actually use versioning, just a master branch) I'd much rather see it built as part of the pcsx2 package and just statically linked in instead of adding another package.

2024-10-01 18:08 UTC, ReillyBrogan approved these changes

2024-10-01 18:09 UTC, merged