KDE Gear 23.08.1
getsolus/packages pull request #388
Opened 2023-09-25 13:48 UTC by joebonrichie

**Summary**

Updates KDE Gear Applications to 23.08.1

**Test Plan**

Use a few applications as normal

**Checklist**

- [x] Package was built and tested against unstable

2023-09-26 18:04 UTC, ReillyBrogan requested changes

2023-09-26 18:04 UTC, ReillyBrogan commented on packages/m/merkuro/package.yml
> +    - kalendar
Please add a commit deleting Kalendar from the repo

2023-09-26 18:04 UTC, ReillyBrogan commented on packages/m/merkuro/package.yml
> +    - dbginfo : kalendar-dbginfo
Please also add `kalendar` and `kalendar-dbginfo` to the solus-sc deprecations

2023-09-27 19:23 UTC, ReillyBrogan approved these changes
LGTM, feel free to land

2023-09-29 23:22 UTC, ReillyBrogan requested changes
I did a bunch of rebuilds of KDE Gear applications for my updates to gmime, gpgme, gnupg, and qtkeychain. This needs a rebase unfortunately

2023-09-30 19:01 UTC, joebonrichie commented
Reminder to self: Update ktextaddons and do it's rebuilds after this lands.

2023-10-01 21:07 UTC, ReillyBrogan submitted a review, later dismissed

2023-10-03 11:51 UTC, joebonrichie commented
Merged manually.

2023-10-03 11:51 UTC, closed without merging