nitrogen: deprecate
getsolus/packages pull request #3985
Opened 2024-10-04 10:56 UTC by androidnisse

**Summary**
- Deprecate nitrogen
- Resolves https://github.com/getsolus/packages/issues/2625

**Test Plan**
- Ran script, checked files were deleted.

**Checklist**

- [X] Package was built and tested against unstable

2024-10-07 18:52 UTC, davidjharder requested changes
Whitespace issue.
Neeeds a rebase as well now.

2024-10-07 18:52 UTC, davidjharder commented on repo_data/distribution.xml.in
> +    <Package>nitrogen-dbginfo</Package>
The whitespace here is funky, should be tabs, not spaces.

2024-10-30 18:44 UTC, davidjharder commented
Sorry, this needs a rebase again

2024-10-31 06:33 UTC, androidnisse commented
> Sorry, this needs a rebase again

Done.

2024-10-31 12:58 UTC, davidjharder approved these changes
Thanks!

2024-10-31 12:59 UTC, merged