ibus-bamboo: add at 0.8.4
getsolus/packages pull request #4017
Opened 2024-10-08 23:05 UTC by minhhut

**Summary**
- add ibus-bamboo at v0.8.4 (https://github.com/BambooEngine/ibus-bamboo/releases/tag/v0.8.4-RC1)
- known issue with Wayland native (see BambooEngine/ibus-bamboo#44)

**Summary**

**Test Plan**

- Install ibus and run "IBus Preferences"
- Add Vietnamese - Bamboo from Input Method tab
- Add "Keyboard Layouts" plugin/widge to see the input switch icon
- Play around with language switch and many options from IBus Bamboo popup menu
- Focus on text input from browser, terminal or other app
- Type "xin chào các bạn"

**Checklist**

- [ ] Package was built and tested against unstable

2024-10-09 01:13 UTC, malfisya commented on packages/i/ibus-bamboo/MAINTAINERS.md
> +- Name Surname
This should be replaced by your (actual) name: Minh Nguyen

2024-10-15 22:59 UTC, EbonJaeger requested changes
We prefer to use pkgconfig names for dependencies whenever possible. :)

Also, could you please squash your commits so that there is only one commit for the package? Thanks!

2024-10-15 22:59 UTC, EbonJaeger commented on packages/i/ibus-bamboo/package.yml
> +    - libx11-devel
Please replace with `pkgconfig(x11)`

2024-10-15 22:59 UTC, EbonJaeger commented on packages/i/ibus-bamboo/package.yml
> +    - libxtst-devel
Please replace with `pkgconfig(xtst)`

2024-10-16 21:50 UTC, minhhut commented
Updated as review's comments. Thanks for the hints!

2024-10-17 14:51 UTC, EbonJaeger approved these changes
LGTM! Thanks for the contribution! :)

2024-10-17 14:51 UTC, merged