Update package dhcpcd to version 10.1.0
getsolus/packages pull request #4363
Opened 2024-11-15 20:09 UTC by aquilapl

**Summary**

**Test Plan**

**Checklist**

- [ ] Package was built and tested against unstable

2024-11-15 20:12 UTC, ReillyBrogan commented
Do you use this package by chance? We don't really use it for anything (NetworkManager has an internal DHCP client that we use) so I'm tempted to just remove it unless there's a legitimate need for it

2024-11-15 20:21 UTC, aquilapl commented
I am learning and took a package from https://shared.getsol.us/justin/updates/ that would not give me any difficulties. And the difference in the version was significant. I don't need it. I don't know what I could update, something that doesn't have a maintainer, and the System (users) need it. The main thing I'm worried about is whether I followed all the git commands, because I was doing it for the first time.

2024-11-26 17:07 UTC, davidjharder requested changes
@malfisya since you are taking over this PR, can you build and then include pspec changes so you are listed in the spec

2024-11-27 02:13 UTC, davidjharder approved these changes

2024-11-27 02:13 UTC, merged