font-ubuntu-sans-ttf: Add at 1.006
getsolus/packages pull request #4409
Opened 2024-11-20 01:09 UTC by uni-dos

**Summary**
- Add ubuntu-sans font
- resolves https://github.com/getsolus/packages/issues/4360

**Test Plan**

Install font, and view in kde font manager.

**Checklist**

- [x] Package was built and tested against unstable

2024-11-20 01:12 UTC, uni-dos commented
The font needs to be added to[Anitya

2024-11-20 14:10 UTC, malfisya commented
Added to anitya [here](https://release-monitoring.org/project/375586/). :+1:

2024-11-21 04:06 UTC, malfisya requested changes
One small nit

2024-11-21 04:06 UTC, malfisya commented on packages/f/font-ubuntu-sans-ttf/package.yml
> +license    : Ubuntu Font License-1.0
The correct identifier is `Ubuntu-font-1.0` according to [spdx](https://spdx.org/licenses/)

2024-11-21 21:59 UTC, malfisya approved these changes
LGTM. Thank you!

2024-11-21 21:59 UTC, merged