Updated monitoring yaml files
getsolus/packages pull request #4433
Opened 2024-11-22 18:00 UTC by TheGreatDefector

Updated yml files, replacing "rss: null" with "rss: ~" as per issue:
https://github.com/getsolus/packages/issues/4425

2024-11-22 20:54 UTC, davidjharder commented
Hey, welcome to Solus! I changed your PR description so that the issue will be automatically closed.

2024-11-23 02:23 UTC, davidjharder commented on packages/w/wireless-regdb/monitoring.yml
>    id: 15257 # Check https://release-monitoring.org/
For this file 15257 is correct, so please delete the rest of the line.

I can't find an rss feed, so leave `rss: ~` and delete the rest of the line

2024-11-23 02:25 UTC, davidjharder commented on packages/l/lzip/monitoring.yml
>    id: 1866 # Check https://release-monitoring.org/
1866 is correct, so the rest of the line can be deleted

2024-11-23 02:28 UTC, davidjharder requested changes
A few small corrections.

Also, please amend your commit title and PR title to something like `repo-wide: Fix monitoring.yml files` This is how we style commits that affect more than one package. If it was just one package, then it would be `packagename: Fix monitoring.yml`

2024-12-03 17:42 UTC, TheGreatDefector commented
Sorry for the delay, PR and commit renamed now for clarity. Thanks!

2024-12-03 17:58 UTC, merged