nvidia-470-glx-driver: Add appstream metainfo
getsolus/packages pull request #527
Opened 2023-10-12 15:04 UTC by joebonrichie

**Summary**

Add appstream metainfo for software centers

**Test Plan**

Run `appstream-builder --packages-dir=. --include-failed -v` verify it completes successfully.

**Checklist**

- [x] Package was built and tested against unstable

2023-10-12 17:03 UTC, ReillyBrogan commented on packages/n/nvidia-470-glx-driver/package.yml
> +    install -Dm00644 nvidia-settings.png $installdir/usr/share/pixmaps/nvidia-current.png
My understanding is that `/usr/share/pixmaps` is deprecated and is only supported for backwards compatibility. Icons should generally be installed to `/usr/share/icons/hicolor/`, to the appropriate folder depending on png size. Preferably you should use a `.svg` icon, even if you have to ship it in the $pkgdir.

2023-10-12 17:03 UTC, ReillyBrogan requested changes
See note

2023-10-13 19:26 UTC, ReillyBrogan requested changes
Same comments as #508

2024-01-21 14:25 UTC, joebonrichie commented
Should be good for merge now

2024-01-21 20:01 UTC, ReillyBrogan approved these changes
LGTM, Thanks!

2024-01-21 20:02 UTC, merged