Add metainfo to sarasa-gothic font
getsolus/packages pull request #669
Opened 2023-10-26 01:44 UTC by TraceyC77

## Summary:

Add appstream metainfo to sarasa-gothic as part of #449

## Test Plan:

Installed font eopkg. Verified fonts appear in Font Management
Ran `appstream-builder --packages-dir=. --include-failed -v` and verified there are no errors

**Checklist**

- [x] Package was built and tested against unstable

2023-10-26 17:42 UTC, ReillyBrogan commented
Needs rebase.

2023-10-26 17:42 UTC, ReillyBrogan requested changes
Needs Rebase

2023-10-26 19:18 UTC, joebonrichie requested changes
Small nit to add translations as this a CJK font and they are provided. Otherwise looks good

2023-10-26 19:18 UTC, joebonrichie commented on packages/f/font-sarasa-gothic/files/sarasa-gothic.metainfo.xml
> +  <summary>Sarasa Gothic / 更纱黑体 / 更紗黑體 / 更紗ゴシック / 사라사 고딕.</summary>
```xml
<summary>This is SARASA GOTHIC, a CJK programming font based on Iosevka and Source Han Sans.</summary>
<summary xml:lang="ja">更紗ゴシック</summary>
<summary xml:lang="kr">사라사 고딕</summary>
<summary xml:lang="zh">更纱黑体</summary>
```

2023-10-27 20:54 UTC, TraceyC77 commented
> Needs Rebase

Done

2023-10-31 18:57 UTC, joebonrichie approved these changes

2023-10-31 18:57 UTC, merged