[RFC] wildmidi: Update to 0.45
getsolus/packages pull request #733
Opened 2023-11-01 06:05 UTC by malfisya

**Summary**

- Changelog:
  - 0.45: 
    - Fixed MUS drum channels 9 and 15 being swapped if the same file is played twice from the same memory buffer 
    - Player: Fixed save midi reading wrong argv if there are no paths separators
  - 0.44:
    - Fixed integer overflow in midi parser sample count calculation
    - Fixed 8 bit ping pong GUS patch loaders - Fixed wrong variable use in reverb code - Reset block status of tty after playback - Fixed broken file name handling for 'save as midi' command during playback
    - Clamp MUS volume commands - CMake project improvements - `cmake` version 3.1 or newer is now required
- Added `homepage` key to `package.yml` (Part of #411)
- Added `freepats` to `rundeps` and `pkgconfig(alsa) to `builddeps`

**Test Plan**

- Run `wildimidi -t` to run sample midi
- Play several midi files to test playback control
- Verified the added homepage loads information about the package

**Checklist**

- [x] Package was built and tested against unstable

2023-11-10 19:15 UTC, joebonrichie requested changes
mpd: Update to 0.23.14 <- Looks like this was accidentally included

2023-11-10 21:26 UTC, malfisya commented
No, i meant to include it. `mpd` depends on `wildmidi`, I should just safety rebuild `mpd`. But there is also an update on `mpd`, so i just update it while rebuild it against new `wildmidi`. Should i just rebuild `mpd` without updating it?

2023-11-10 23:10 UTC, joebonrichie approved these changes

2023-11-12 20:41 UTC, merged

2023-11-12 20:41 UTC, davidjharder commented
Gonna merge this