blender: Enable CUDA support
getsolus/packages pull request #847
Opened 2023-11-19 18:42 UTC by joebonrichie

**Summary**
- Add CUDA as a source to avoid redistributing CUDA in a seperate package.

**Test Plan**
- Run classroom with CUDA cycles rendered enabled. Verify the GPU is being used.

**Checklist**

- [x] Package was built and tested against unstable

2023-11-19 19:10 UTC, joebonrichie commented
Needs some testing with if you have the 470 driver installed or you're using nouveau. Just to verify things don't explode.

2023-11-23 14:58 UTC, GZGavinZhao commented
I cannot test it, but it looks fine to me judging by the `pspec_x86_64.xml`.

2024-05-10 22:07 UTC, davidjharder commented
YOLO

2024-05-17 18:47 UTC, joebonrichie commented
Hmm generating an abi report fails: `failed to open 'kernel_sm_50.cubin', reason: 'mismatched ELF version 'EV_CURRENT+122' in record at byte 0x0'`

2024-05-17 20:57 UTC, GZGavinZhao commented
I think that fail is expected, since CUDA binaries are not ELF binaries.

2024-05-18 12:46 UTC, joebonrichie commented
> I think that fail is expected, since CUDA binaries are not ELF binaries.

Problem is it kills `abi-wizard` and no updated `abi_*` files get generated.

2024-05-18 12:48 UTC, joebonrichie commented
Issue is coming from one of these: https://github.com/search?q=repo%3ADataDrake%2Fabi-wizard%20failed%20to%20open&type=code

2024-05-25 19:20 UTC, algent-al requested changes

2024-05-25 19:20 UTC, algent-al commented on packages/b/blender/package.yml
>  license    : GPL-2.0-or-later
Licenses may need some update.

2024-05-25 20:25 UTC, algent-al approved these changes
LGTM, thanks!

2024-05-25 20:25 UTC, merged