klayout: Update to 0.28.13
getsolus/packages pull request #897
Opened 2023-11-26 17:42 UTC by hashhsah

**Summary**

There are dozens of new features and enhancements between 0.28.9 and 0.28.13. A complete list of changes can be found at https://www.klayout.de/development.html

**Test Plan**

- Open a few GDS and OAS files (kB to GB in size) and browse the layout.
- Open Help->About and check it ruby/python bindings are present in the `Build options` and ~20 .so files are present in `Binary Extensions`.
- Start python3, import `klayout` and `pya` modules.

**Checklist**

- [ ] Package was built and tested against unstable

2023-12-08 00:32 UTC, ReillyBrogan requested changes
Hi @hashhsah , it seems that reviewers have kept skipping over this PR in the review queue and for that I am deeply sorry. It should not have taken us this long to get around to reviewing this, we are very appreciative that you have taken the time to update these packages! 

Besides the two comments I left on the files I'd also like to mention that the commit order is incorrect. Package PRs should not have merge commits in the commit log, you'll need to rebase this PR so that only the commits that are actually changing packages are present in the commits to be added. If you need any help with how to do that please feel free to hop onto our Matrix and we'll be more than happy to help, or you can ask here and we can walk you through it as well!

2023-12-08 00:32 UTC, ReillyBrogan commented on packages/k/klayout/package.yml
> +    - pkgconfig(libgit2)
`pkgconfig` dependencies are ordered alphabetically with capitalized dependency names going first and then lower-case once going after those. So `pkgconfig(libgit2)` should be moved up and placed after `pkgconfig(Qt5XmlPatterns)` and before `pkgconfig(python3)`.

2023-12-08 00:32 UTC, ReillyBrogan commented on packages/y/yosys/package.yml
> +version    : '0.35'
This yosys update seems unrelated to the `klayout` update? Did you mean to include it or was it included accidentally? Neither package seems to have a run or builddep on the other, and while I'm not familiar enough with what they're doing they seem to no be needed for each other? If this was included accidentally, could you please move the yosys update to a separate PR?

2023-12-08 00:33 UTC, ReillyBrogan commented
Oh I just noticed that this PR has a conflict with main. To fix that you'll need to rebase the commit, bump it and rebuild it so that the release number in the updated package.yml is 1 greater than what is currently in the main branch.

2023-12-30 16:21 UTC, closed without merging

2023-12-30 20:27 UTC, ReillyBrogan commented
Did you mean to close this?

2023-12-31 01:43 UTC, hashhsah commented
sorry about the late reply, have been busy with work. Meanwhile klayout 0.28.14 has been released. I took note of the comments above and created a new PR #1153.